Update links and add spacing
wende/elchemy pull request #371
Opened 2019-12-26 13:35 UTC by ShalokShalom

Changed a few things, moved some parts, improved readability. 

Added links, mention Elm in Elm once more and add its contributor to the contributor list, as well as fixed some sentences and introduced Elm like spacing in order to improve the readability of the source. 

The line "In case of any questions about the project feel free to submit them in Issues with Q&A label" could create a new issue for the user - with q&a label already applied. Has to be done by a privileged person. 

Oh, and most important: Adds emoticons. :heart:

2020-01-07 12:25 UTC, wende requested changes
Looks good 🎉 
Just one comment

2020-01-07 12:25 UTC, wende commented on README.md
> +- [Elm-in-Elm](https://github.com/elm-in-elm/compiler) creator Martin Janiczek - [@janiczek](https://github.com/Janiczek)
We don't use elm-in-elm at all. But it definitely is a good place to mention @Bogdanp for creating elm-ast which was the first dependency and the most influential inspiration in creating Elchemy

2020-01-07 12:32 UTC, wende commented on README.md
> +- [Elm-in-Elm](https://github.com/elm-in-elm/compiler) creator Martin Janiczek - [@janiczek](https://github.com/Janiczek)
Also, feel free to mention yourself @ShalokShalom as recently you've been giving Elchemy more love than I was able to deliver 😄 

OT: I've been rewriting type inference from scratch and there's been some great developments in term of having it clear and concise. Really stoked to get this to MVP stage 🎉

2020-01-16 19:00 UTC, ShalokShalom commented
Oh, I see

I have a talent to misread and interpret Slack chat conversations and Github issues, no idea where I got the feeling elm-in-elm is used.

So elm-ast is inspiration to your own implemenation - and why is the code for that one not public?

I think it would help showing that the project is still going on.

Your are doing great work!

P.S: Thanks for your motivation, I will add my name once I deliver the documentation for complete newbie which I talked about like a year ago. Or two.

2020-01-16 19:47 UTC, ShalokShalom commented
Oh, I do see you now maintain the elm-ast repo

I guess there is the code, you are talking about?

2020-01-26 12:15 UTC, ShalokShalom commented
@wende i added new changes, did you already look at them?

I have made an own section for people and projects who inpired your work, and seperated it from the list of contributors.

2020-02-03 15:46 UTC, merged